# .travis.yml
# Configure Travis CI service for http://github.com/LASzip
language: cpp

compiler:
  - g++
  - clang

#before_install: ./scripts/ci/before_install.sh

script: ./scripts/ci/script.sh

notifications:
  on_success: always # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
  irc: "chat.freenode.net#pdal"
  # Uncomment and edit below for notifications by e-mail
  #email:
  #  recipients:
  #    - howard@hobu.co

