/* gdal_def.h.  Generated by cmake4gdal  */

/* Define if gdal used libz*/
#define GDAL_USE_LIBZ

/* Define to 1 gdal used internal libz*/
#define GDAL_USE_LIBZ_INTERNAL 0

/* Define if gdal used libcurl */
/* #undef GDAL_USE_CURL */

/* Define if gdal used odbc */
/* #undef GDAL_USE_ODBC */

/* Define if gdal used xmlreformat */
/* #undef GDAL_USE_XMLREFORMAT */

/* Define if gdal used cpl */
#define GDAL_USE_CPL

/* Define if pam enable in gdal */
#define GDAL_PAM_ENABLED

/* Define if gdal use geos*/
#define GDAL_HAVE_GEOS 1

/* Define if gdal use opencl*/
/* #undef GDAL_HAVE_OPENCL */

/* Define if gdal use armadillo*/
/* #undef GDAL_HAVE_ARMADILLO */

/* Define if gdal use iconv*/
/* #undef GDAL_HAVE_ICONV */

/* Define if gdal use internal libtiff*/
/* #undef GDAL_USE_LIBTIFF_INTERNAL */
#define GDAL_HAVE_TIFF
#define GDAL_BIGTIFF_SUPPORT
#define GDAL_PIXARLOG_SUPPORT

/* Define if gdal use internal libjpeg*/
/* #undef GDAL_USE_LIBJPEG_INTERNAL */
#define GDAL_HAVE_JPEG
#define GDAL_JPEG_SUPPORT
#define GDAL_OJPEG_SUPPORT

/* Define if gdal use internal libpng*/
/* #undef GDAL_USE_LIBPNG_INTERNAL */
/* #undef GDAL_HAVE_PNG */

/* Define if gdal use internal libgif*/
/* #undef GDAL_USE_LIBGIF_INTERNAL */
/* #undef GDAL_HAVE_GIF */

#define GDAL_HAVE_EXPAT
#define GDAL_HAVE_SQLITE
/* #undef GDAL_HAVE_PG */
#define GDAL_HAVE_SQLITE
/* #undef GDAL_HAVE_MYSQL */
/* #undef GDAL_HAVE_BOOST */
/* #undef GDAL_HAVE_HAVE_LIBKML */

#define GDAL_ENABLE_OGR
#define OGR_USE_JSONC_INTERNAL

/*** RASTER FORMATS ***/
#define GDAL_ENABLE_FRMT_GTIFF
/* #undef GDAL_ENABLE_FRMT_JPEG */
#define GDAL_ENABLE_FRMT_HFA
#define GDAL_ENABLE_FRMT_BMP
/* #undef GDAL_ENABLE_FRMT_DIMAP */
#define GDAL_ENABLE_FRMT_MEM
#define GDAL_ENABLE_FRMT_RAW
/* #undef GDAL_ENABLE_FRMT_VRT */
/* #undef GDAL_ENABLE_FRMT_PNG */
/* #undef GDAL_ENABLE_FRMT_GIF */
/* #undef GDAL_ENABLE_FRMT_TIL */

/*** VECTOR FORMATS ***/
#define OGR_ENABLE_MITAB
#define OGR_ENABLE_CSV
#define OGR_ENABLE_DFX
/* #undef OGR_ENABLE_GEOJSON */
#define OGR_ENABLE_MEM
#define OGR_ENABLE_VRT
#define OGR_ENABLE_GPX
#define OGR_ENABLE_SHP
#define OGR_ENABLE_WFS
/* #undef OGR_ENABLE_PG */
/* #undef OGR_ENABLE_SQLITE */
/* #undef OGR_ENABLE_MYSQL */
/* #undef OGR_ENABLE_LIBKML */
/* #undef OGR_ENABLE_GML */
/* #undef OGR_ENABLE_KML */
